# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: UTF8
  host: localhost
  # port: 5423
  # schema_search_path: "classificados"
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5 #<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: classificados_development
  username: postgres
  password: <%= ENV['SECRET_KEY_BASE'] %>

test:
  <<: *default
  database: classificados_test
  username: postgres
  password: <%= ENV['SECRET_KEY_BASE'] %>

production:
  <<: *default
  database: classificados_production
  username: postgres
  password: <%= ENV['CLASSIFICADOS_DATABASE_PASSWORD'] %>
